//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country_Codes
    {
        public string COUNTRY { get; set; }
        public string A2_ISO { get; set; }
        public string A3_UN { get; set; }
        public Nullable<short> NUM_UN { get; set; }
        public Nullable<short> DIALING_CODE { get; set; }
    }
}
