//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors
    {
        public long DRID { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> Publications { get; set; }
        public string RecentDate { get; set; }
        public string NPI { get; set; }
        public Nullable<long> REVIEWER_ID { get; set; }
        public string Specialty { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email_Address { get; set; }
        public string County { get; set; }
        public string Company_Name { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string Timezone { get; set; }
        public string Website { get; set; }
        public string Gender { get; set; }
        public string Credentials { get; set; }
        public string Taxonomy_Code { get; set; }
        public string Taxonomy_Classification { get; set; }
        public string Taxonomy_Specialization { get; set; }
        public string License_Number { get; set; }
        public string License_State { get; set; }
        public string Medical_School { get; set; }
        public string Residency_Training { get; set; }
        public string Graduation_Year { get; set; }
    }
}
